name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - pair:
              otp: 24.2
              elixir: 1.13
          - pair:
              otp: 26.2
              elixir: 1.16
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          MIX_ENV=test mix deps.get
          MIX_ENV=test mix deps.compile
          MIX_ENV=test mix compile
      - name: Start epmd
        run: |
          epmd -daemon
      - name: Run tests
        run: |
          MIX_ENV=test mix test
