name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - pair:
              otp: 27
              elixir: 1.17
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install → Compile dependencies
        run: |
          MIX_ENV=test mix deps.get
          MIX_ENV=test mix deps.compile
          MIX_ENV=test mix compile
      - name: Start epmd
        run: |
          epmd -daemon
      - name: Run tests
        run: |
          MIX_ENV=test mix test
      - name: Run tests with Telemetry
        run: |
          cd examples/tm
          MIX_ENV=test mix deps.get
          MIX_ENV=test mix test
      - name: Run tests with OpenTelemetry
        run: |
          cd examples/otel
          MIX_ENV=test mix deps.get
          MIX_ENV=test mix test
